### PR TITLE
Add unit tests for the API

### PR DESCRIPTION
**Pull request by cweiske**
This should making updates easier, since we can now automatically test big parts of the API.

### CODE REVIEW

**Comment by CybotTM** [comment]
Why https://github.com/netresearch/timetracker/commit/4df671a634d0053491f5a61bc810ab7169f6d49a ?

**Comment by CybotTM** [comment]
ah, never mind, got it, just not sure if i agree.

**Comment by CybotTM** [comment]
I hope you took a look at the implemented test (infrastructure) in main.

**Comment by cweiske** [comment]
Nope, we started fresh.

**Pull request merged**
